/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartCampaignRouteImport } from './routes/start-campaign'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as JoinCreatorRouteImport } from './routes/join-creator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StartCampaignRoute = StartCampaignRouteImport.update({
  id: '/start-campaign',
  path: '/start-campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCreatorRoute = JoinCreatorRouteImport.update({
  id: '/join-creator',
  path: '/join-creator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/join-creator': typeof JoinCreatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-campaign': typeof StartCampaignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/join-creator': typeof JoinCreatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-campaign': typeof StartCampaignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/join-creator': typeof JoinCreatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-campaign': typeof StartCampaignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/join-creator'
    | '/sitemap.xml'
    | '/start-campaign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/join-creator'
    | '/sitemap.xml'
    | '/start-campaign'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/join-creator'
    | '/sitemap.xml'
    | '/start-campaign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  JoinCreatorRoute: typeof JoinCreatorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartCampaignRoute: typeof StartCampaignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start-campaign': {
      id: '/start-campaign'
      path: '/start-campaign'
      fullPath: '/start-campaign'
      preLoaderRoute: typeof StartCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-creator': {
      id: '/join-creator'
      path: '/join-creator'
      fullPath: '/join-creator'
      preLoaderRoute: typeof JoinCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  JoinCreatorRoute: JoinCreatorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartCampaignRoute: StartCampaignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
